-- MySQL Script generated by MySQL Workbench
-- Tue May 15 13:53:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PlanificationVolsAeriens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PlanificationVolsAeriens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlanificationVolsAeriens` DEFAULT CHARACTER SET utf8 ;
USE `PlanificationVolsAeriens` ;

-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Airport` (
  `idAirport` INT NOT NULL AUTO_INCREMENT,
  `airportName` VARCHAR(100) NOT NULL,
  `airportAcronym` VARCHAR(3) NOT NULL,
  `airportCountry` VARCHAR(30) NOT NULL,
  `fkAirportType` INT NOT NULL,
  PRIMARY KEY (`idAirport`),
  FOREIGN KEY (`fkAirportType`)
  REFERENCES `PlanificationVolsAeriens`.`AirportType` (`idAirportType`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Pilot` (
  `idPilot` INT NOT NULL AUTO_INCREMENT,
  `pilotName` VARCHAR(45) NOT NULL,
  `pilotFirstName` VARCHAR(45) NOT NULL,
  `flightTime` FLOAT NOT NULL,
  `fkAirport` INT NOT NULL,
  `fkAirportCurrentLocation` INT NOT NULL,
  PRIMARY KEY (`idPilot`, `fkAirport`, `fkAirportCurrentLocation`),
  INDEX `fk_Pilot_Airport1_idx` (`fkAirport` ASC),
  INDEX `fk_Pilot_Airport2_idx` (`fkAirportCurrentLocation` ASC),
  CONSTRAINT `fk_Pilot_Airport1`
    FOREIGN KEY (`fkAirport`)
    REFERENCES `PlanificationVolsAeriens`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pilot_Airport2`
    FOREIGN KEY (`fkAirportCurrentLocation`)
    REFERENCES `PlanificationVolsAeriens`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Line` (
  `idLine` INT NOT NULL AUTO_INCREMENT,
  `distance` INT NOT NULL,
  `fkDepartureAirport` INT NOT NULL,
  `fkArrivalAirport` INT NOT NULL,
  PRIMARY KEY (`idLine`, `fkDepartureAirport`, `fkArrivalAirport`),
  INDEX `fk_Line_Airport1_idx` (`fkDepartureAirport` ASC),
  INDEX `fk_Line_Airport2_idx` (`fkArrivalAirport` ASC),
  CONSTRAINT `fk_Line_Airport1`
    FOREIGN KEY (`fkDepartureAirport`)
    REFERENCES `PlanificationVolsAeriens`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Line_Airport2`
    FOREIGN KEY (`fkArrivalAirport`)
    REFERENCES `PlanificationVolsAeriens`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Flight` (
  `idFlight` INT NOT NULL AUTO_INCREMENT,
  `flightName` VARCHAR(30) NOT NULL,
  `departureDate` DATETIME NOT NULL,
  `arrivalDate` DATETIME NOT NULL,
  `fkLine` INT NOT NULL,
  PRIMARY KEY (`idFlight`, `fkLine`),
  INDEX `fk_Flight_Line1_idx` (`fkLine` ASC),
  CONSTRAINT `fk_Flight_Line1`
    FOREIGN KEY (`fkLine`)
    REFERENCES `PlanificationVolsAeriens`.`Line` (`idLine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Flight_has_Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Flight_has_Pilot` (
  `fkFlight` INT NOT NULL,
  `fkPilot` INT NOT NULL,
  PRIMARY KEY (`fkFlight`, `fkPilot`),
  INDEX `fk_Flight_has_Pilot_Pilot1_idx` (`fkPilot` ASC),
  INDEX `fk_Flight_has_Pilot_Flight1_idx` (`fkFlight` ASC),
  CONSTRAINT `fk_Flight_has_Pilot_Flight1`
    FOREIGN KEY (`fkFlight`)
    REFERENCES `PlanificationVolsAeriens`.`Flight` (`idFlight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_has_Pilot_Pilot1`
    FOREIGN KEY (`fkPilot`)
    REFERENCES `PlanificationVolsAeriens`.`Pilot` (`idPilot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanificationVolsAeriens`.`Vacation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`Vacation` (
  `idVacation` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `fkPilot` INT NOT NULL,
  PRIMARY KEY (`idVacation`, `fkPilot`),
  INDEX `fk_Vacation_Pilot1_idx` (`fkPilot` ASC),
  CONSTRAINT `fk_Vacation_Pilot1`
    FOREIGN KEY (`fkPilot`)
    REFERENCES `PlanificationVolsAeriens`.`Pilot` (`idPilot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `PlanificationVolsAeriens`.`AirportType` (
	`idAirportType` INT NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`idAirportType`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into AirportType(idAirportType, type) values (1, 'Aeroport international');

insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (1, 'Saint-Gall-Altenrhein', 'ACH', 'Suisse',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (2, 'd\'Al-Ain', 'AAN','Emirats arabes unis',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (3, 'd\'Abakan', 'ABA','Russie',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (4, 'd\'Asaba', 'ABB','Nigeria',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (5, 'Felix-Houphouet-Boigny', 'ABJ','Cote d\'Ivoire',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (6, 'd\'Albuquerque', 'ABQ','Etats-Unis',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (7, 'general Juan N. Alvarez', 'ACA', 'Mexique',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (8, 'de Kotoka', 'ACC','Ghana',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (9, 'd\'Atlantic City', 'ACY', 'Etats-Unis',1);
insert into Airport (idAirport, airportName, airportAcronym, airportCountry, fkAirportType) values (10, 'd\'Adana-Sakirpasa', 'ADA','Turquie',1);



